- name: Core SRX
  hosts: "927"
  # gather_facts: no

  # collections:
  # - junipernetworks.junos

  tasks:
  - name: Version
      junipernetworks.junos.junos_command:
        commands:
        - show version